spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      properties:
        hibernate:
          transaction:
            jta:
              platform: org.jboss.narayana.jta
          format_sql: true
          hbm2ddl:
            auto: update
      show-sql: false

server:
  port: ${SERVER_PORT}